apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-price-app
  labels:
    app: my-price-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-price-app
  template:
    metadata:
      labels:
        app: my-price-app
    spec:
      containers:
      - name: my-price-app
        image: sevmars/bitcoin-price-image:latest
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: sevmars/rest-api-image:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: my-price-app
spec:
  type: ClusterIP
  selector:
    app: my-price-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api
spec:
  type: ClusterIP
  selector:
    app: rest-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001